### PR TITLE
Fix #631, Add new functional tests for OS_chmod

### LINKED ISSUE #631: OS_chmod missing functional test
**Is your feature request related to a problem? Please describe.**
Missing functional test (coverage test exists).

**Describe the solution you'd like**
Add functional test

**Describe alternatives you've considered**
None

**Additional context**
Required for cert

**Requester Info**
Jacob Hageman - NASA/GSFC

### PR DESCRIPTION
**Pull request by zanzaben**
**Describe the contribution**
Fixes #631 by adding new function tests

**Testing performed**
These new test, but ran them on the branch from #650 

**Expected behavior changes**
The new tests added to make test

**Additional context**
Dependant on #650 

**System(s) tested on**
Ubuntu 20.04

**Contributor Info - All information REQUIRED for consideration of pull request**
Alex Campbell GSFC

### CODE REVIEW

**Comment by astrogeco** [comment]
[CCB 20201202](https://github.com/nasa/cFS/wiki/Community-CCB-Agenda:-December-02-2020) - APPROVED
- depends on nasa/osal#663

**Comment by jphickey** [comment]
Unfortunately this PR appears to have broken the file-api-test on RTEMS ....
```
[BEGIN] 04 TestChmod
OS_FileOpen_Impl():111:open(/RAM/Filename1): Invalid argument
[ FAIL] 04.001 file-api-test.c:257 - status after creat = -1
[ FAIL] 04.002 file-api-test.c:259 - status after close = -16
```

**Comment by astrogeco** [comment]
> Unfortunately this PR appears to have broken the file-api-test on RTEMS ....
> 
> ```
> [BEGIN] 04 TestChmod
> OS_FileOpen_Impl():111:open(/RAM/Filename1): Invalid argument
> [ FAIL] 04.001 file-api-test.c:257 - status after creat = -1
> [ FAIL] 04.002 file-api-test.c:259 - status after close = -16
> ```

Can you open an issue? @zanzaben do you have a way to test on RTEMS?

**Comment by zanzaben** [comment]
> > Unfortunately this PR appears to have broken the file-api-test on RTEMS ....
> > ```
> > [BEGIN] 04 TestChmod
> > OS_FileOpen_Impl():111:open(/RAM/Filename1): Invalid argument
> > [ FAIL] 04.001 file-api-test.c:257 - status after creat = -1
> > [ FAIL] 04.002 file-api-test.c:259 - status after close = -16
> > ```
> 
> Can you open an issue? @zanzaben do you have a way to test on RTEMS?

I do not have a way to test on RTEMS

**Pull request merged**
