### PR TITLE
Fix #429, add OS_time_t access functions

### LINKED ISSUE #429: Use a better time representation in OS_stat call
**Is your feature request related to a problem? Please describe.**
The `OS_stat` call currently returns the file time as an `int32` member within the `os_fstat_t` structure, as defined here:

https://github.com/nasa/osal/blob/a66eb2dc00136a77779414452835bb6364d5e1fb/src/os/inc/osapi-os-filesys.h#L154

This isn't really documented in the API but the field is a traditional UNIX-style timestamp, which is seconds elapsed since Jan 1 1970 UTC.

This type of timestamp suffers from the "year 2038" bug, where the int32 value rolls over and becomes negative.  Although this is 18 years from now, at the timescales of space software development cycles, it is entirely possible that coding being developed now will still be in service at the time this happens, so it should be fixed sooner rather than later.

**Describe the solution you'd like**
There are two fixes needed:

1. use the `OS_time_t` representation as used in `OS_GetLocalTime` and `OS_SetLocalTime`.  This is just for consistency - shouldn't use a different representation of time as the other API calls do.
2. Fix the `OS_time_t` to accommodate larger timestamp values and/or use a different epoch (latter would be risk but keep the structure the same size).

**Additional context**
Discussion regarding use of this field in nasa/cfe#519

**Requester Info**
Joseph Hickey, Vantage Systems, Inc.

### PR DESCRIPTION
**Pull request by jphickey**
**Describe the contribution**

Initially the first commit just adds access functions to convert/extract different units from an `OS_time_t` value - so that other code in CFE/PSP/Apps can be updated to use the access functions and thereby not break when the internal time definition changes.  There will then be a second commit that updates the actual time format.

It also uses OS_time_t in the "stat" structure used by the file module rather than having this be a `int32`.

Minor detail - also updates the pointer argument to `OS_SetLocalTime()` to be `const`

Fixes #429

**Testing performed**
Build and sanity check CFE

**Expected behavior changes**
Initially just a set of new access functions - no impact to behavior
Eventually will change the internal format of `OS_time_t` which will break any code that is _not_ using the access functions.
Prototype change of `OS_SetLocalTime()` should be backward compatible.

**System(s) tested on**
Ubuntu 20.04 
RTEMS 4.11.3 

**Additional context**
Initial commit which just adds the access functions and updates OSAL can be merged at any time, it does not have any dependencies and does not break anything.

Second commit will depend on nasa/cfe#1051 and nasa/psp#227 (may be a separate PR depending on how review/merge cycles go)

**Contributor Info - All information REQUIRED for consideration of pull request**
Joseph Hickey, Vantage Systems, Inc.

### CODE REVIEW

**Comment by jphickey** [comment]
This initial change can be reviewed and merged at any time; does not depend on any other change an does not break anything, but we need to get these access functions in place first in order to fix CFE/PSP code.

**Comment by jphickey** [comment]
Amended to also include a conversion from "subseconds" (2^-32) back to `OS_time_t` - since the opposite was provide, should provide conversion for both directions here.

`static inline OS_time_t OS_TimeAssembleFromSubseconds(int64 seconds, uint32 subseconds)`

This can replace `CFE_TIME_Micro2SubSecs` and `CFE_TIME_Sub2MicroSecs` but without the bugs noted in https://github.com/nasa/cFE/issues/1051#issuecomment-753043048

**Comment by skliper** [comment]
Did you add unit tests and stubs for all the new APIs?

**Comment by jphickey** [comment]
> Did you add unit tests and stubs for all the new APIs?

There are no stubs because these are all `static inline` access functions.  Most are exercised by existing tests.  However I will add a few more test cases to the clock coverage test to make sure they all get called.

**Review by skliper — APPROVED** [review]

**Comment by astrogeco** [comment]
[CCB 2021-01-06](https://github.com/nasa/cFS/wiki/Community-CCB-Agenda:-January-06-2021) APPROVED

**Comment by jphickey** [comment]
Two comments regarding recent review:

1. I forgot to mention, that while this adds individual access functions get time in units of milli/micro/nano/sub seconds, it only provides creation function for nano and subseconds - not milli/micro/whole seconds.  I figured these were trivial, but in retrospect, maybe we should provide all of them for completeness?
2. Regarding the unit test of File Time in the OS_stat() call - the purpose of this test is to make sure that the time returned by the system `fstat()` call (in `struct stat`) gets translated into the `OS_stat_t` structure returned by OSAL.  The input is a fixed value - always the same.  The test case just makes sure the same value appears in the output struct, too.  But because only a POSIX 2008 build will copy the full resolution - only this is verified in the test case, so the test case doesn't need conditional logic.  I think verifying the seconds made it through is enough, as we don't have a specific requirement for high-res timestamps at this time.

**Comment by jphickey** [comment]
Update - commit f09c57e adds two more conversions to create an `OS_time_t` from milli- and microseconds.  Just the same as the `OS_TimeAssembleFromNanoseconds` with different units.  I decided this was probably worthwhile since all the conversions _from_ an `OS_time_t` to these units were provided, we should also provide the full set in the opposite direction, too, even if the conversion is pretty trivial.

**Review by skliper — APPROVED** [review]

**Comment by astrogeco** [comment]
@jphickey please check conflicts

**Comment by astrogeco** [comment]
> @jphickey please check conflicts

Nevermind, I think I got it. See b30e58d1fe139bb1eed25f6a00f19454b9322fbf and CI run at https://github.com/nasa/cFS/pull/174/checks?sha=1a5438081bd92d28fa59b5d3042ea24629d38763

**Pull request merged**
