### PR TITLE
fix #737 - deprecates UT_Stub_GetForceFail() and allows NULL for the …

### LINKED ISSUE #737: deprecate UT_Stub_CheckForceFail()
With the deprecation of `UT_Stub_SetForceFail()`, its functionality was replaced with `UT_Stub_SetDefaultReturnValue()`.

The `UT_Stub_CheckForceFail()` should likewise be deprecated. 

https://github.com/nasa/osal/blob/d698a4d7ddc66826a4c7c287468b5f1aa6ca372f/ut_assert/inc/utstubs.h#L321

### PR DESCRIPTION
**Pull request by CDKnightNASA**
…value pointer

Closes #737 

**Describe the contribution**
The `UT_Stub_SetForceFail()` was deprecated and replaced with `UT_Stub_SetDefaultReturnValue()`. Same has been done for `UT_Stub_ClearForceFail()` and `UT_Stub_CheckForceFail()`. Also, made it so that NULL can be passed as the `value` out parameter to `UT_Stub_CheckDefaultReturnValue()` for when a user just wants to check whether it's set or not but doesn't care what the value is.

**Testing performed**
Built and ran SB UT.

**Contributor Info - All information REQUIRED for consideration of pull request**
Christopher.D.Knight@nasa.gov

### CODE REVIEW

**Comment by CDKnightNASA** [comment]
Note I've added a second commit which cascades all the required changes for osal to switch to the `...DefaultReturnValue()` functions. cfe, psp, and sample_app all have unit test code that also needs updating, unsure how best to proceed.

**Review by zanzaben — APPROVED** [review]

**Comment by zanzaben** [comment]
>  cfe, psp, and sample_app all have unit test code that also needs updating, unsure how best to proceed.

You need to make separate issues and pull request for each of those branches. Look at nasa/osal#725 to see how the other requests link back to the main one.

**Comment by CDKnightNASA** [comment]
I would like to wait for #724 to be merged into main and I can revisit this ticket and resolve conflicts and merge.

**Comment by astrogeco** [comment]
@CDKnightNASA #724 is in main now

**Comment by skliper** [comment]
Closing as duplicate of #823

**Pull request closed without merging**
