### PR TITLE
issue #307, Remove unsupported BSPs

### PR DESCRIPTION
**Pull request by avan989**
**Describe the contribution**
Remove unsupported BSP and change genppc-vxworks6.4→ mcp750-vxworks 

**System(s) tested on:**
 - Hardware
 - Ubuntu 18.04

**Contributor Info**
Anh Van, NASA Goddard

### CODE REVIEW

**Comment by skliper** [comment]
CCB 20191218 - Reviewed and approved for IC

**Comment by jphickey** [comment]
NOTE: the old name of the BSP is referenced in the CFE example toolchains here:

https://github.com/nasa/cFE/blob/2b27dfc8f2a4e0627e6c4b646765269213584cda/cmake/sample_defs/toolchain-ppc-vxworks6.9.cmake#L49

This external reference also needs to be updated accordingly.

**Comment by avan989** [comment]
updated. Reference https://github.com/nasa/cFE/pull/444

**Comment by skliper** [comment]
Merged to master prematurely, reverted and merged to ic branch.

**Pull request merged**
