### PR TITLE
Fix #1281, Rtems On task creation register name.

### LINKED ISSUE #1281: Rtems should show task names when typing `cpuuse`
**Describe the bug**
typing `cpuuse` in console should show rtems names.

Add the following bits to `OS_TaskCreate_Impl` in rtems
```C
#include <rtems/score/threadimpl.h>
...
    ISR_lock_Context  lock_context_1;
    Thread_Control *the_thread;
...
    the_thread = _Thread_Get(impl->id, &lock_context_1 );
    _Thread_Set_name(the_thread, task->task_name);
    
```

**Expected behavior**
rtems should register its name, so it shows up when using rtems commands.

**Code snips**
If applicable, add references to the software.

**System observed on:**
 - Hardware microblaze
 - OS: rtems 6

**Additional context**
Better debug info in rtems

**Reporter Info**
Nasa

### PR DESCRIPTION
**Pull request by thesamprice**
**Checklist (Please check before submitting)**

* [X] I reviewed the [Contributing Guide](https://github.com/nasa/osal/blob/main/CONTRIBUTING.md).
* [ ] I signed and emailed the appropriate [Contributor License Agreement](https://github.com/nasa/cFS/blob/main/CONTRIBUTING.md#contributor-license-agreement-cla) to GSFC-SoftwareRelease@mail.nasa.gov and copied cfs-program@lists.nasa.gov.

**Describe the contribution**
Registers task name with rtems on creation
 Fixes #1281 

**Testing performed**
Steps taken to test the contribution:
Ran on microblaze, typed cpuuse in rtems task, saw names.

**Expected behavior changes**
A clear and concise description of how this contribution will change behavior and level of impact.
 - API Change: xxx (if applicable)
 - Behavior Change: xxx (if applicable)
 - Or no impact to behavior

**System(s) tested on**
 - Hardware: microblaze kcu105
 - OS:RTEMS

**Additional context**
Add any other context about the contribution here.

**Third party code**
If included, identify any third party code and provide text file of license

**Contributor Info - All information REQUIRED for consideration of pull request**
Nasa/ GSFC

### CODE REVIEW

**Comment by dzbaker** [comment]
CCB 25 Aug 2022: Need to test in RTEMS on our end, have someone review.

**Comment by skliper** [comment]
Related workflows: https://github.com/nasa/cFS/blob/main/.github/workflows/build-cfs-rtems4.11.yml https://github.com/nasa/cFS/blob/main/.github/workflows/build-cfs-rtems5.yml

**Comment by thesamprice** [comment]
I did this wrong,
This call should be used. 
`rtems_status_code rtems_object_set_name( rtems_id id, const char *name );`

https://github.com/RTEMS/rtems/blob/6abdd89f191a5e6d64055093f68a4fce10554f82/cpukit/include/rtems/rtems/object.h#L437

The functions starting with `_` are private rtems functions.
Also my method is missing a lock.  See the pthread version. 
https://github.com/RTEMS/rtems/blob/f381e9bab29278e4434b1a93e70d17a7562dc64c/cpukit/posix/src/pthreadsetnamenp.c#L40

**Comment by thesamprice** [comment]
I guess the pthread setname does the same
@DrRTEMS  I think Setting the name on create requires 4 char names.  where these calls allow for longer names.
The osal layer allows for longer names
DrRTEMS — Today at 12:24 PM
I would make sure the longer names work with Classic API tasks/ Inside the score, an object class can have no name, 32-bits, or strings. It probably will only take the first four characters if it works
thesamprice — Today at 12:24 PM
is there any requirement on them being unique?
right now osal gives all the tasks unique ids rather than human readable names
DrRTEMS — Today at 12:25 PM
None unless you want to use the "ident" services. They find the first match.

**Comment by travis-r-wheatley** [comment]
Replaced call to _Thread_set_name() with a call to rtems_object_set_name()

**Comment by dzbaker** [comment]
CCB 6 October 2022: Need to verify that this still works in RTEMS 4.11. @travis-r-wheatley will check which version of RTEMS he tested with.

**Comment by travis-r-wheatley** [comment]
Verified that RTEMS 6 was used for testing.

**Comment by thesamprice** [comment]
@dzbaker  This function call exists in the 4.11 version of rtems.
https://github.com/RTEMS/rtems/blob/4.11/cpukit/rtems/src/rtemsobjectsetname.c
https://github.com/RTEMS/rtems/blob/4.11/cpukit/rtems/include/rtems/rtems/object.h#L155

**Review by dzbaker — CHANGES_REQUESTED** [review]
Thank you for your contribution @thesamprice and @travis-r-wheatley, this looks great! I ran the unit test suite on RTEMS 5 and did come across a few new unit test failures:

oscore-test:
[ FAIL] 42.001 ut_oscore_task_test.c:500 - OS_TaskGetId() (0) == 65608
[ FAIL] 39.001 ut_oscore_task_test.c:379 - OS_TaskGetInfo(g_task_ids[1], &task_prop) (0) == OS_ERR_INVALID_ID (-16)
[ FAIL] 38.002 ut_oscore_task_test.c:316 - OS_TaskInstallDeleteHandler() (-16) == OS_SUCCESS
[ FAIL] 38.003 ut_oscore_task_test.c:317 - OS_TaskInstallDeleteHandler() callback invoked

Would you be able to look into these? I will be creating an RTEMS Unit Test workflow for OSAL, so that should make it easier to check in the future.

**Comment by thesamprice** [comment]
@dzbaker  Did this pass on the current dev/main branch or is this branch the first to run the test suite.

**Comment by dzbaker** [comment]
> @dzbaker Did this pass on the current dev/main branch or is this branch the first to run the test suite.

@thesamprice I had run this on both the current main branch and 1281-rtems-task-names. The 4 failures only showed up for me on 1281-rtems-task-names (there were other failures in other tests, but those occurred in the main branch as well). These 4 failures also didn't show up several weeks ago when I ran the unit tests on the original commit for this PR.

**Comment by thesamprice** [comment]
@dzbaker 
I think the issue is how tasks are gotten.
https://github.com/nasa/osal/blob/main/src/os/rtems/src/os-impl-tasks.c#L303

I think this should be scanning through and using `impl->id` rather than task names.
impl->id is set at startup, and then were changing the name.
    status = rtems_task_create(r_name, task->priority, task->stack_size, r_mode, r_attributes, &impl->id);
Is there a cfs reverse map call for this type of logic?

**Comment by skliper** [comment]
Just took a quick skim... and yeah, if you are changing the name this get task id implementation won't work.  Maybe a pattern like the Linux or VxWorks implementation makes more sense?  I'd start there for ideas.

**Comment by chillfig** [comment]
Will not merge.

**Pull request closed without merging**
