### PR TITLE
Fix #449, Rename BSPs to be generic

### LINKED ISSUE #449: Make BSPs more generic
**Is your feature request related to a problem? Please describe.**
Users requiring custom PSP packages should not need to create both -- a CFE PSP and OSAL BSP.  The existing OSAL BSP should be used whenever possible.

The "mcp750-vxworks" BSP (at least) is not particularly hardware-specific and should be usable on any vxworks platform.  Likewise "pc-linux" should be usable on any generic linux platform.

The main purpose of the OSAL BSP is just to provide an entry point to get into the common/modular code.

**Describe the solution you'd like**
Rename these BSPs to be generic and allow use by many PSPs.

**Describe alternatives you've considered**
User needs to add a custom BSP for each board.

**Requester Info**
Joseph Hickey, Vantage Systems, Inc.

### PR DESCRIPTION
**Pull request by jphickey**
**Describe the contribution**
Rename BSPs that can be used on multiple platforms.  
mcp750-vxworks becomes generic-vxworks
pc-linux becomes generic-linux

(pc-rtems stays the same for now)

**Testing performed**
Build for all supported operating systems (linux, vxworks, rtems) and confirm all unit tests pass and CFE runs normally.

**Expected behavior changes**
No impact to behavior, but build scripts in external entities need to change the name.

**System(s) tested on**
Ubuntu 20.04 (native)
RTEMS 4.11 on pc686 / QEMU
VxWorks 6.9 on MCP750

**Additional context**
See related issue nasa/psp#162 and PR nasa/psp#164 which changes the refs to these.

**Contributor Info - All information REQUIRED for consideration of pull request**
Joseph Hickey, Vantage Systems, Inc.

### CODE REVIEW

**Comment by jphickey** [comment]
Created as a draft due to baseline issues.  Only commit for review here is b8cd3d4.

**Comment by astrogeco** [comment]
CCB  20200520 - APPROVED, needs to be merged on top of related PRs

**Comment by astrogeco** [comment]
@jphickey can I merge this?

**Comment by jphickey** [comment]
Lets hold off to next cycle, I prefer to rebase to "master" to fix this.

**Comment by jphickey** [comment]
Rebased to current master, should be good to go now.

**Comment by skliper** [comment]
@astrogeco This is a project priority, Can it move forward?

**Pull request merged**
