### PR TITLE
Fix #742, make sure all pointers are checked for null

### LINKED ISSUE #742: Scrub API's for null pointer checks
**Is your feature request related to a problem? Please describe.**
All pointers should be checked for NULL prior to accessing, a few cases where this was observed have been fixed but need to do a complete scrub.

**Describe the solution you'd like**
Scrub and add any missing null pointer checks

**Describe alternatives you've considered**
None

**Additional context**
Use the new macros...

**Requester Info**
Jacob Hageman - NASA/GSFC

### LINKED ISSUE #765: API's Null pointer check in void methods
**Is your feature request related to a problem? Please describe.**
Some pointers are used in methods that return void so the OS_CHECK_POINTER function doesn't work in those methods since it returns an error code. There needs to be a way to check that pointers are valid inside void methods. 

**Describe the solution you'd like**
Need to discuss the best solution 

**Additional context**
related to #742, That branch has this comment marking everywhere it comes up. 
    /* TODO: void pointer, https://github.com/nasa/osal/issues/765 */

**Requester Info**
Alex Campbell GSFC

### PR DESCRIPTION
**Pull request by zanzaben**
**Describe the contribution**
Fixes #742 
Went through all the api's and made sure all pointers have a null check, or a comment stating that it can be null. 

Fixes #765 

**Testing performed**
Build and run unit test

**Expected behavior changes**
none

**System(s) tested on**
Ubuntu 20.04

**Additional context**
13 To Do left in here that will be fixed by #765 

**Contributor Info - All information REQUIRED for consideration of pull request**
Alex Campbell GSFC

### CODE REVIEW

**Comment by jphickey** [comment]
Note - we should __not__ be doing pointer checks on internal functions - only those that are part of the public API.

I took a glance at the proposed commit and I see it is adding checks to internal routines.  This is inefficient and unnecessary - as the value should have been already checked in the public API it was called from.  It is also my understanding that code standards only require it on externally-called functions.

**Comment by skliper** [comment]
> Note - we should **not** be doing pointer checks on internal functions - only those that are part of the public API.
> 
> I took a glance at the proposed commit and I see it is adding checks to internal routines. This is inefficient and unnecessary - as the value should have been already checked in the public API it was called from. It is also my understanding that code standards only require it on externally-called functions.

Concur.  The coding standard applies to all the APIs.

**Comment by zanzaben** [comment]
After removing all the internal checks this pull request is just a bunch of formatting fixes and changing comments to all use the same terminology.

**Comment by skliper** [comment]
Can you add the BUGCHECKs in the void public APIs?  That would close out the issue.

**Comment by zanzaben** [comment]
> Can you add the BUGCHECKs in the void public APIs? That would close out the issue.

Done

**Comment by astrogeco** [comment]
[CCB:2021-01-27](https://github.com/nasa/cFS/wiki/Community-CCB-Agenda:-January-27-2021) APPROVED
-

**Pull request merged**
