### PR TITLE
Fix #960, add socket shutdown implementation

### LINKED ISSUE #960: Add socket shutdown API
**Is your feature request related to a problem? Please describe.**
No support for graceful shutdown of TCP sockets

**Describe the solution you'd like**
Add shutdown API

**Describe alternatives you've considered**
None

**Additional context**
Stakeholder request

**Requester Info**
Jacob Hageman - NASA/GSFC

ping @excaliburtb

### PR DESCRIPTION
**Pull request by jphickey**
**Describe the contribution**
Adds an OS_SocketShutdown() wrapper around the BSD socket shutdown() API.  This allows a data transfer of a stream socket to be gracefully shut down prior to socket closure.

Fixes #960

**Testing performed**
Build and sanity check CFE, run all unit tests
The "network-api-test" program is enhanced with several more test cases to confirm that the shutdown functionality is working as intended.

**Expected behavior changes**
`OS_SocketShutdown()` API added.  No effect unless API is used, existing code not changed.

**System(s) tested on**
Ubuntu 20.04, RTEMS 4.11

**Additional context**
This PR depends on PR #971, so this is based on the IC right now.

**Contributor Info - All information REQUIRED for consideration of pull request**
Joseph Hickey, Vantage Systems, Inc.

### CODE REVIEW

**Comment by skliper** [comment]
Ping @excaliburtb

**Review by skliper — APPROVED** [review]

**Comment by astrogeco** [comment]
[CCB:2021-04-28](https://github.com/nasa/cFS/wiki/Community-CCB-Agenda:-April-28-2021) APPROVED

**Comment by jphickey** [comment]
Rebased/pushed again to resolve some code coverage issues.  This looks OK now.

**Comment by jphickey** [comment]
The branch was deleted by mistake, this is still needing merge

**Pull request merged**
