### PR TITLE
Integration Candidate: 2020-09-02

### LINKED ISSUE #537: Overall Tests Pass Even With a TSF
**Describe the bug**
The software is set up such that overall tests pass even if there is a test case that TSF.  I have had individual TSFs, and yet the overall tests showed everything passed.  

See code here: https://github.com/nasa/osal/blob/80fdd67a6c28a962164697ece12570142331ea44/ut_assert/src/utbsp.c#L213

**System observed on:**
cFS Dev Server
OS: Ubuntu 18.04
Versions: OSAL 5.0.11.0

**Reporter Info**
Yasir Majeed Khan
NASA GSFC/Emergent Space

### LINKED ISSUE #555: OSAL should provide a typedef for "ID" values
**Is your feature request related to a problem? Please describe.**
The OSAL API uses `uint32` type to identify objects/resources in an abstract way.

**Describe the solution you'd like**
There should be a typedef for this.  For instance:

    typedef uint32 OS_id_t;

This typedef can then be used in all APIs rather than using `uint32` directly.

**Describe alternatives you've considered**
Keep using `uint32`.

**Additional context**
Providing a typedef is generally accepted as good practice in terms of future proofing the code.  This wouldn't change anything immediately, as the type will remain `uint32` as it currently is.

**Requester Info**
Joseph Hickey, Vantage Systems, Inc.

### LINKED ISSUE #581: osal_timer_UT test setup failure
**Is your feature request related to a problem? Please describe.**
```
[BEGIN] 01 OS_TimerCreate
[ PASS] 01.001 ut_ostimer_timerio_test.c:255 - #1 Null-pointer-arg
[ PASS] 01.002 ut_ostimer_timerio_test.c:264 - #2 Name-too-long
[ PASS] 01.003 ut_ostimer_timerio_test.c:277 - #3 Name equal to OS_MAX_API_NAME characters test
[ PASS] 01.004 ut_ostimer_timerio_test.c:288 - #4 Name-taken
[  TSF] 01.005 ut_ostimer_timerio_test.c:310 - #4 No-free-IDs - Timer-created failed
[ PASS] 01.006 ut_ostimer_timerio_test.c:330 - #6 Invalid-arg
[ INFO] 01.007 ut_ostimer_timerio_test.c:337 - #7 Timer-unavailable
[ PASS] 01.008 ut_ostimer_timerio_test.c:348 - #8 Nominal
[  END] 01 OS_TimerCreate       TOTAL::8     PASS::6     FAIL::0      MIR::0      TSF::1      N/A::0
```

**Describe the solution you'd like**
Fix failure, related to #579 

**Describe alternatives you've considered**
None

**Additional context**
None

**Requester Info**
Jacob Hageman - NASA/GSFC

### PR DESCRIPTION
**Pull request by yammajamma**
**Describe the contribution**
Fix #555 
Fix #537 
Fix #581 

**Testing performed**
Bundle CI - https://github.com/nasa/cFS/pull/136/checks

**Expected behavior changes**
PR #568 - Introduces a new `typedef, osal_id_t`, in `common_types.h`, which should be used to represent an OSAL ID. All API structures/functions are updated to use this typedef in place of the uint32 type wherever it actually refers to an OSAL ID.

PR #579 - Fail tests on startup or tear down failures. These are failures, just a different severity (likely mean the test didn't work as expected and needs to be fixed).

PR #583  - Max timer create test was using `OS_MAX_TIMERS` (the limit for adding timers to a time base), but creating timers is limited by `OS_MAX_TIMEBASES` since the create adds a new time base.

HOTFIX 20200902 - Fix documentation warnings in OSAL.

HOTFIX 20200902 - Hide the call graph on utility functions.

**System(s) tested on**
Ubuntu - CI

**Additional context**
https://github.com/nasa/cFS/pull/136

**Contributor Info - All information REQUIRED for consideration of pull request**
Jacob Hageman, NASA-GSFC
Joseph Hickey, Vantage Systems, Inc.

### CODE REVIEW

**Comment by astrogeco** [comment]
@skliper and @jphickey looks like we have some usersguide doxygen errors at the bundle level

```
/home/travis/build/nasa/cFS/osal/src/os/inc/osapi-os-filesys.h:929: warning: end of file while inside a group

/home/travis/build/nasa/cFS/cfe/fsw/cfe-core/src/inc/cfe_sb_msg.h:654: warning: unable to resolve link to `#CFE_SB_MAX_PIPE_DEPTH' for \link command

/home/travis/build/nasa/cFS/cfe/cmake/sample_defs/cpu1_platform_cfg.h:900: warning: explicit link request to 'CFE_SB_MAX_SB_MSG_SIZE' could not be resolved

/home/travis/build/nasa/cFS/cfe/fsw/cfe-core/src/inc/cfe_es_events.h:442: warning: unable to resolve link to `#CFE_ES_SHELL_CC' for \link command

/home/travis/build/nasa/cFS/cfe/fsw/cfe-core/src/inc/cfe_es_events.h:111: warning: unable to resolve link to `#CFE_ES_SHELL_CC' for \link command

/home/travis/build/nasa/cFS/cfe/fsw/cfe-core/src/inc/cfe_fs_extern_typedefs.h:103: warning: unable to resolve link to `#CFE_ES_SHELL_CC' for \link command

/home/travis/build/nasa/cFS/cfe/docs/src/cfe_glossary.dox:74: warning: explicit link request to 'CFE_EVS_DEBUG' could not be resolved

/home/travis/build/nasa/cFS/cfe/docs/src/cfe_glossary.dox:74: warning: explicit link request to 'CFE_EVS_INFORMATION' could not be resolved

/home/travis/build/nasa/cFS/cfe/docs/src/cfe_glossary.dox:75: warning: explicit link request to 'CFE_EVS_ERROR' could not be resolved

/home/travis/build/nasa/cFS/cfe/docs/src/cfe_glossary.dox:75: warning: explicit link request to 'CFE_EVS_CRITICAL' could not be resolved

/home/travis/build/nasa/cFS/cfe/docs/src/cfe_api.dox:3: warning: @copybrief or @copydoc target 'CFE_FS_IsGzFile' not found

/home/travis/build/nasa/cFS/cfe/docs/src/cfe_api.dox:3: warning: @copybrief or @copydoc target 'CFE_FS_Decompress' not found

/home/travis/build/nasa/cFS/cfe/docs/src/cfe_api.dox:3: warning: @copybrief or @copydoc target 'CFE_FS_GetUncompressedFile' not found

/home/travis/build/nasa/cFS/cfe/docs/src/cfe_api.dox:3: warning: @copybrief or @copydoc target 'CFE_SB_GetLastSenderId' not found

/home/travis/build/nasa/cFS/cfe/docs/src/cfe_api.dox:3: warning: @copybrief or @copydoc target 'CFE_TIME_CFE2FSSeconds' not found

/home/travis/build/nasa/cFS/cfe/docs/src/cfe_api.dox:3: warning: @copybrief or @copydoc target 'CFE_TIME_FS2CFESeconds' not found

/home/travis/build/nasa/cFS/cfe/docs/src/cfe_api.dox:109: warning: unable to resolve reference to `CFEAPIFSCompress' for \ref command

/home/travis/build/nasa/cFS/cfe/docs/src/cfe_api.dox:111: warning: explicit link request to 'CFE_FS_IsGzFile' could not be resolved

/home/travis/build/nasa/cFS/cfe/docs/src/cfe_api.dox:112: warning: explicit link request to 'CFE_FS_Decompress' could not be resolved

/home/travis/build/nasa/cFS/cfe/docs/src/cfe_api.dox:113: warning: explicit link request to 'CFE_FS_GetUncompressedFile' could not be resolved

/home/travis/build/nasa/cFS/cfe/docs/src/cfe_api.dox:172: warning: explicit link request to 'CFE_SB_GetLastSenderId' could not be resolved

/home/travis/build/nasa/cFS/cfe/docs/src/cfe_api.dox:250: warning: explicit link request to 'CFE_TIME_CFE2FSSeconds' could not be resolved

/home/travis/build/nasa/cFS/cfe/docs/src/cfe_api.dox:251: warning: explicit link request to 'CFE_TIME_FS2CFESeconds' could not be resolved

/home/travis/build/nasa/cFS/cfe/docs/src/cfe_es.dox:169: warning: explicit link request to 'CFE_ES_VOLATILE_STARTUP_FILE' could not be resolved

/home/travis/build/nasa/cFS/cfe/docs/src/cfe_es.dox:172: warning: explicit link request to 'CFE_ES_NONVOL_STARTUP_FILE' could not be resolved

/home/travis/build/nasa/cFS/cfe/docs/src/cfe_es.dox:222: warning: explicit link request to 'CFE_ES_POWERON_RESET' could not be resolved

/home/travis/build/nasa/cFS/cfe/docs/src/cfe_es.dox:223: warning: explicit link request to 'CFE_ES_PROCESSOR_RESET' could not be resolved

/home/travis/build/nasa/cFS/cfe/docs/src/cfe_es.dox:231: warning: explicit link request to 'CFE_ES_POWER_CYCLE' could not be resolved

/home/travis/build/nasa/cFS/cfe/docs/src/cfe_es.dox:231: warning: explicit link request to 'CFE_ES_PUSH_BUTTON' could not be resolved

/home/travis/build/nasa/cFS/cfe/docs/src/cfe_es.dox:231: warning: explicit link request to 'CFE_ES_HW_SPECIAL_COMMAND' could not be resolved

/home/travis/build/nasa/cFS/cfe/docs/src/cfe_es.dox:232: warning: explicit link request to 'CFE_ES_HW_WATCHDOG' could not be resolved

/home/travis/build/nasa/cFS/cfe/docs/src/cfe_es.dox:232: warning: explicit link request to 'CFE_ES_RESET_COMMAND' could not be resolved

/home/travis/build/nasa/cFS/cfe/docs/src/cfe_es.dox:232: warning: explicit link request to 'CFE_ES_EXCEPTION' could not be resolved

/home/travis/build/nasa/cFS/cfe/docs/src/cfe_es.dox:233: warning: explicit link request to 'CFE_ES_UNDEFINED_RESET' could not be resolved

/home/travis/build/nasa/cFS/cfe/docs/src/cfe_es.dox:233: warning: explicit link request to 'CFE_ES_HWDEBUG_RESET' could not be resolved

/home/travis/build/nasa/cFS/cfe/docs/src/cfe_es.dox:233: warning: explicit link request to 'CFE_ES_BANKSWITCH_RESET' could not be resolved

/home/travis/build/nasa/cFS/cfe/docs/src/cfe_es.dox:248: warning: explicit link request to 'CFE_ES_DEFAULT_ER_LOG_FILE' could not be resolved

/home/travis/build/nasa/cFS/cfe/docs/src/cfe_es.dox:253: warning: explicit link request to 'CFE_ES_ER_LOG_ENTRIES' could not be resolved

/home/travis/build/nasa/cFS/cfe/docs/src/cfe_es.dox:258: warning: explicit link request to 'CFE_ES_ER_LOG_ENTRIES' could not be resolved

/home/travis/build/nasa/cFS/cfe/docs/src/cfe_es.dox:499: warning: explicit link request to 'CFE_ES_PERF_DATA_BUFFER_SIZE' could not be resolved

/home/travis/build/nasa/cFS/cfe/docs/src/cfe_es.dox:558: warning: explicit link request to 'CFE_ES_DEFAULT_PERF_DUMP_FILENAME' could not be resolved

/home/travis/build/nasa/cFS/cfe/docs/src/cfe_es.dox:737: warning: unable to resolve link to `#CFE_ES_PoolStatsTlm_t' for \link command

/home/travis/build/nasa/cFS/cfe/docs/src/cfe_es.dox:749: warning: unable to resolve link to `#CFE_ES_PoolStatsTlm_t' for \link command

/home/travis/build/nasa/cFS/cfe/docs/src/cfe_es.dox:788: warning: explicit link request to 'CFE_ES_DEFAULT_SYSLOG_FILE' could not be resolved

/home/travis/build/nasa/cFS/cfe/docs/src/cfe_es.dox:793: warning: explicit link request to 'CFE_ES_SYSTEM_LOG_SIZE' could not be resolved

/home/travis/build/nasa/cFS/cfe/docs/src/cfe_es.dox:169: warning: explicit link request to 'CFE_ES_VOLATILE_STARTUP_FILE' could not be resolved

/home/travis/build/nasa/cFS/cfe/docs/src/cfe_es.dox:172: warning: explicit link request to 'CFE_ES_NONVOL_STARTUP_FILE' could not be resolved

/home/travis/build/nasa/cFS/cfe/docs/src/cfe_es.dox:222: warning: explicit link request to 'CFE_ES_POWERON_RESET' could not be resolved

/home/travis/build/nasa/cFS/cfe/docs/src/cfe_es.dox:223: warning: explicit link request to 'CFE_ES_PROCESSOR_RESET' could not be resolved

/home/travis/build/nasa/cFS/cfe/docs/src/cfe_es.dox:231: warning: explicit link request to 'CFE_ES_POWER_CYCLE' could not be resolved

/home/travis/build/nasa/cFS/cfe/docs/src/cfe_es.dox:231: warning: explicit link request to 'CFE_ES_PUSH_BUTTON' could not be resolved

/home/travis/build/nasa/cFS/cfe/docs/src/cfe_es.dox:231: warning: explicit link request to 'CFE_ES_HW_SPECIAL_COMMAND' could not be resolved

/home/travis/build/nasa/cFS/cfe/docs/src/cfe_es.dox:232: warning: explicit link request to 'CFE_ES_HW_WATCHDOG' could not be resolved

/home/travis/build/nasa/cFS/cfe/docs/src/cfe_es.dox:232: warning: explicit link request to 'CFE_ES_RESET_COMMAND' could not be resolved

/home/travis/build/nasa/cFS/cfe/docs/src/cfe_es.dox:232: warning: explicit link request to 'CFE_ES_EXCEPTION' could not be resolved

/home/travis/build/nasa/cFS/cfe/docs/src/cfe_es.dox:233: warning: explicit link request to 'CFE_ES_UNDEFINED_RESET' could not be resolved

/home/travis/build/nasa/cFS/cfe/docs/src/cfe_es.dox:233: warning: explicit link request to 'CFE_ES_HWDEBUG_RESET' could not be resolved

/home/travis/build/nasa/cFS/cfe/docs/src/cfe_es.dox:233: warning: explicit link request to 'CFE_ES_BANKSWITCH_RESET' could not be resolved

/home/travis/build/nasa/cFS/cfe/docs/src/cfe_es.dox:248: warning: explicit link request to 'CFE_ES_DEFAULT_ER_LOG_FILE' could not be resolved

/home/travis/build/nasa/cFS/cfe/docs/src/cfe_es.dox:253: warning: explicit link request to 'CFE_ES_ER_LOG_ENTRIES' could not be resolved

/home/travis/build/nasa/cFS/cfe/docs/src/cfe_es.dox:258: warning: explicit link request to 'CFE_ES_ER_LOG_ENTRIES' could not be resolved

/home/travis/build/nasa/cFS/cfe/docs/src/cfe_es.dox:499: warning: explicit link request to 'CFE_ES_PERF_DATA_BUFFER_SIZE' could not be resolved

/home/travis/build/nasa/cFS/cfe/docs/src/cfe_es.dox:558: warning: explicit link request to 'CFE_ES_DEFAULT_PERF_DUMP_FILENAME' could not be resolved

/home/travis/build/nasa/cFS/cfe/docs/src/cfe_es.dox:737: warning: unable to resolve link to `#CFE_ES_PoolStatsTlm_t' for \link command

/home/travis/build/nasa/cFS/cfe/docs/src/cfe_es.dox:749: warning: unable to resolve link to `#CFE_ES_PoolStatsTlm_t' for \link command

/home/travis/build/nasa/cFS/cfe/docs/src/cfe_es.dox:788: warning: explicit link request to 'CFE_ES_DEFAULT_SYSLOG_FILE' could not be resolved

/home/travis/build/nasa/cFS/cfe/docs/src/cfe_es.dox:793: warning: explicit link request to 'CFE_ES_SYSTEM_LOG_SIZE' could not be resolved

/home/travis/build/nasa/cFS/cfe/docs/src/cfe_evs.dox:145: warning: explicit link request to 'CFE_EVS_DEFAULT_TYPE_FLAG' could not be resolved

/home/travis/build/nasa/cFS/cfe/docs/src/cfe_evs.dox:173: warning: explicit link request to 'CFE_EVS_MAX_EVENT_FILTERS' could not be resolved

/home/travis/build/nasa/cFS/cfe/docs/src/cfe_evs.dox:343: warning: explicit link request to 'CFE_EVS_MAX_EVENT_FILTERS' could not be resolved

/home/travis/build/nasa/cFS/cfe/docs/src/cfe_evs.dox:145: warning: explicit link request to 'CFE_EVS_DEFAULT_TYPE_FLAG' could not be resolved

/home/travis/build/nasa/cFS/cfe/docs/src/cfe_evs.dox:173: warning: explicit link request to 'CFE_EVS_MAX_EVENT_FILTERS' could not be resolved

/home/travis/build/nasa/cFS/cfe/docs/src/cfe_evs.dox:343: warning: explicit link request to 'CFE_EVS_MAX_EVENT_FILTERS' could not be resolved

/home/travis/build/nasa/cFS/cfe/docs/src/cfe_sb.dox:130: warning: explicit link request to 'CFE_SB_MAX_DEST_PER_PKT' could not be resolved

/home/travis/build/nasa/cFS/cfe/docs/src/cfe_sb.dox:161: warning: explicit link request to 'CFE_SB_BUF_MEMORY_BYTES' could not be resolved

/home/travis/build/nasa/cFS/cfe/docs/src/cfe_sb.dox:164: warning: explicit link request to 'CFE_SB_MEM_BLOCK_SIZE_01' could not be resolved

/home/travis/build/nasa/cFS/cfe/docs/src/cfe_sb.dox:182: warning: explicit link request to 'CFE_SB_BUF_MEMORY_BYTES' could not be resolved

/home/travis/build/nasa/cFS/cfe/docs/src/cfe_sb.dox:339: warning: explicit link request to 'CFE_SB_DEFAULT_MSG_LIMIT' could not be resolved

/home/travis/build/nasa/cFS/cfe/docs/src/cfe_sb.dox:481: warning: explicit link request to 'CFE_SB_BUF_MEMORY_BYTES' could not be resolved

/home/travis/build/nasa/cFS/cfe/docs/src/cfe_sb.dox:130: warning: explicit link request to 'CFE_SB_MAX_DEST_PER_PKT' could not be resolved

/home/travis/build/nasa/cFS/cfe/docs/src/cfe_sb.dox:161: warning: explicit link request to 'CFE_SB_BUF_MEMORY_BYTES' could not be resolved

/home/travis/build/nasa/cFS/cfe/docs/src/cfe_sb.dox:164: warning: explicit link request to 'CFE_SB_MEM_BLOCK_SIZE_01' could not be resolved

/home/travis/build/nasa/cFS/cfe/docs/src/cfe_sb.dox:182: warning: explicit link request to 'CFE_SB_BUF_MEMORY_BYTES' could not be resolved

/home/travis/build/nasa/cFS/cfe/docs/src/cfe_sb.dox:339: warning: explicit link request to 'CFE_SB_DEFAULT_MSG_LIMIT' could not be resolved

/home/travis/build/nasa/cFS/cfe/docs/src/cfe_sb.dox:481: warning: explicit link request to 'CFE_SB_BUF_MEMORY_BYTES' could not be resolved

/home/travis/build/nasa/cFS/cfe/docs/src/cfe_tbl.dox:165: warning: explicit link request to 'CFE_TBL_MAX_SIMULTANEOUS_LOADS' could not be resolved

/home/travis/build/nasa/cFS/cfe/docs/src/cfe_tbl.dox:197: warning: explicit link request to 'CFE_TBL_MAX_SIMULTANEOUS_LOADS' could not be resolved

/home/travis/build/nasa/cFS/cfe/docs/src/cfe_tbl.dox:327: warning: explicit link request to 'CFE_TBL_HkPacket_t' could not be resolved

/home/travis/build/nasa/cFS/cfe/docs/src/cfe_tbl.dox:165: warning: explicit link request to 'CFE_TBL_MAX_SIMULTANEOUS_LOADS' could not be resolved

/home/travis/build/nasa/cFS/cfe/docs/src/cfe_tbl.dox:197: warning: explicit link request to 'CFE_TBL_MAX_SIMULTANEOUS_LOADS' could not be resolved

/home/travis/build/nasa/cFS/cfe/docs/src/cfe_tbl.dox:327: warning: explicit link request to 'CFE_TBL_HkPacket_t' could not be resolved

/home/travis/build/nasa/cFS/cfe/docs/src/cfe_time.dox:273: warning: explicit link request to 'CFE_TIME_CFG_DEFAULT_TAI' could not be resolved

/home/travis/build/nasa/cFS/cfe/docs/src/cfe_time.dox:273: warning: explicit link request to 'CFE_TIME_CFG_DEFAULT_UTC' could not be resolved

/home/travis/build/nasa/cFS/cfe/docs/src/cfe_time.dox:296: warning: explicit link request to 'CFE_TIME_CFG_FAKE_TONE' could not be resolved

/home/travis/build/nasa/cFS/cfe/docs/src/cfe_time.dox:322: warning: explicit link request to 'CFE_TIME_AT_TONE_WAS' could not be resolved

/home/travis/build/nasa/cFS/cfe/docs/src/cfe_time.dox:322: warning: explicit link request to 'CFE_TIME_AT_TONE_WILL_BE' could not be resolved

/home/travis/build/nasa/cFS/cfe/docs/src/cfe_time.dox:348: warning: explicit link request to 'CFE_TIME_MIN_ELAPSED' could not be resolved

/home/travis/build/nasa/cFS/cfe/docs/src/cfe_time.dox:348: warning: explicit link request to 'CFE_TIME_MAX_ELAPSED' could not be resolved

/home/travis/build/nasa/cFS/cfe/docs/src/cfe_time.dox:379: warning: explicit link request to 'CFE_TIME_CFG_SERVER' could not be resolved

/home/travis/build/nasa/cFS/cfe/docs/src/cfe_time.dox:379: warning: explicit link request to 'CFE_TIME_CFG_CLIENT' could not be resolved

/home/travis/build/nasa/cFS/cfe/docs/src/cfe_time.dox:486: warning: explicit link request to 'CFE_TIME_CFG_SRC_MET' could not be resolved

/home/travis/build/nasa/cFS/cfe/docs/src/cfe_time.dox:486: warning: explicit link request to 'CFE_TIME_CFG_SRC_GPS' could not be resolved

/home/travis/build/nasa/cFS/cfe/docs/src/cfe_time.dox:486: warning: explicit link request to 'CFE_TIME_CFG_SRC_TIME' could not be resolved

/home/travis/build/nasa/cFS/cfe/docs/src/cfe_time.dox:506: warning: explicit link request to 'CFE_TIME_CFG_SIGNAL' could not be resolved

/home/travis/build/nasa/cFS/cfe/docs/src/cfe_time.dox:273: warning: explicit link request to 'CFE_TIME_CFG_DEFAULT_TAI' could not be resolved

/home/travis/build/nasa/cFS/cfe/docs/src/cfe_time.dox:273: warning: explicit link request to 'CFE_TIME_CFG_DEFAULT_UTC' could not be resolved

/home/travis/build/nasa/cFS/cfe/docs/src/cfe_time.dox:296: warning: explicit link request to 'CFE_TIME_CFG_FAKE_TONE' could not be resolved

/home/travis/build/nasa/cFS/cfe/docs/src/cfe_time.dox:322: warning: explicit link request to 'CFE_TIME_AT_TONE_WAS' could not be resolved

/home/travis/build/nasa/cFS/cfe/docs/src/cfe_time.dox:322: warning: explicit link request to 'CFE_TIME_AT_TONE_WILL_BE' could not be resolved

/home/travis/build/nasa/cFS/cfe/docs/src/cfe_time.dox:348: warning: explicit link request to 'CFE_TIME_MIN_ELAPSED' could not be resolved

/home/travis/build/nasa/cFS/cfe/docs/src/cfe_time.dox:348: warning: explicit link request to 'CFE_TIME_MAX_ELAPSED' could not be resolved

/home/travis/build/nasa/cFS/cfe/docs/src/cfe_time.dox:379: warning: explicit link request to 'CFE_TIME_CFG_SERVER' could not be resolved

/home/travis/build/nasa/cFS/cfe/docs/src/cfe_time.dox:379: warning: explicit link request to 'CFE_TIME_CFG_CLIENT' could not be resolved

/home/travis/build/nasa/cFS/cfe/docs/src/cfe_time.dox:486: warning: explicit link request to 'CFE_TIME_CFG_SRC_MET' could not be resolved

/home/travis/build/nasa/cFS/cfe/docs/src/cfe_time.dox:486: warning: explicit link request to 'CFE_TIME_CFG_SRC_GPS' could not be resolved

/home/travis/build/nasa/cFS/cfe/docs/src/cfe_time.dox:486: warning: explicit link request to 'CFE_TIME_CFG_SRC_TIME' could not be resolved

/home/travis/build/nasa/cFS/cfe/docs/src/cfe_time.dox:506: warning: explicit link request to 'CFE_TIME_CFG_SIGNAL' could not be resolved

/home/travis/build/nasa/cFS/cfe/docs/src/cfe_time.dox:556: warning: explicit link request to 'CFE_TIME_CFG_DEFAULT_TAI' could not be resolved

/home/travis/build/nasa/cFS/cfe/docs/src/cfe_time.dox:556: warning: explicit link request to 'CFE_TIME_CFG_DEFAULT_UTC' could not be resolved

/home/travis/build/nasa/cFS/cfe/docs/src/cfe_time.dox:273: warning: explicit link request to 'CFE_TIME_CFG_DEFAULT_TAI' could not be resolved

/home/travis/build/nasa/cFS/cfe/docs/src/cfe_time.dox:273: warning: explicit link request to 'CFE_TIME_CFG_DEFAULT_UTC' could not be resolved

/home/travis/build/nasa/cFS/cfe/docs/src/cfe_time.dox:296: warning: explicit link request to 'CFE_TIME_CFG_FAKE_TONE' could not be resolved

/home/travis/build/nasa/cFS/cfe/docs/src/cfe_time.dox:322: warning: explicit link request to 'CFE_TIME_AT_TONE_WAS' could not be resolved

/home/travis/build/nasa/cFS/cfe/docs/src/cfe_time.dox:322: warning: explicit link request to 'CFE_TIME_AT_TONE_WILL_BE' could not be resolved

/home/travis/build/nasa/cFS/cfe/docs/src/cfe_time.dox:348: warning: explicit link request to 'CFE_TIME_MIN_ELAPSED' could not be resolved

/home/travis/build/nasa/cFS/cfe/docs/src/cfe_time.dox:348: warning: explicit link request to 'CFE_TIME_MAX_ELAPSED' could not be resolved

/home/travis/build/nasa/cFS/cfe/docs/src/cfe_time.dox:379: warning: explicit link request to 'CFE_TIME_CFG_SERVER' could not be resolved

/home/travis/build/nasa/cFS/cfe/docs/src/cfe_time.dox:379: warning: explicit link request to 'CFE_TIME_CFG_CLIENT' could not be resolved

/home/travis/build/nasa/cFS/cfe/docs/src/cfe_time.dox:486: warning: explicit link request to 'CFE_TIME_CFG_SRC_MET' could not be resolved

/home/travis/build/nasa/cFS/cfe/docs/src/cfe_time.dox:486: warning: explicit link request to 'CFE_TIME_CFG_SRC_GPS' could not be resolved

/home/travis/build/nasa/cFS/cfe/docs/src/cfe_time.dox:486: warning: explicit link request to 'CFE_TIME_CFG_SRC_TIME' could not be resolved

/home/travis/build/nasa/cFS/cfe/docs/src/cfe_time.dox:506: warning: explicit link request to 'CFE_TIME_CFG_SIGNAL' could not be resolved

/home/travis/build/nasa/cFS/cfe/docs/src/cfe_time.dox:556: warning: explicit link request to 'CFE_TIME_CFG_DEFAULT_TAI' could not be resolved

/home/travis/build/nasa/cFS/cfe/docs/src/cfe_time.dox:556: warning: explicit link request to 'CFE_TIME_CFG_DEFAULT_UTC' could not be resolved

warning: Call graph for 'OS_ObjectIdDefined' not generated, too many nodes. Consider increasing DOT_GRAPH_MAX_NODES.

/home/travis/build/nasa/cFS/osal/src/os/inc/osapi-os-filesys.h:226: warning: unable to resolve reference to `OS_file_flag_t' for \ref command

/home/travis/build/nasa/cFS/cfe/fsw/cfe-core/src/inc/cfe_sb_msg.h:654: warning: unable to resolve link to `#CFE_SB_MAX_PIPE_DEPTH' for \link command

/home/travis/build/nasa/cFS/cfe/fsw/cfe-core/src/inc/cfe_sb_msg.h:654: warning: unable to resolve link to `#CFE_SB_MAX_PIPE_DEPTH' for \link command
```

**Comment by jphickey** [comment]
Looks like these are mostly deprecated symbols that are now removed, hence why they've become warnings now.  Doxygen must not have known about the "OMIT_DEPRECATED" flag or else these would have shown up earlier.  Basically a bug that has existed for a long time but only just showing up now.

**Comment by skliper** [comment]
@yammajamma - could you resolve these?  I suggest updating the links if there is a replacement (any of the scoping name changes or API updates), or removing the reference/update the documentation if the functionality was deprecated.

**Comment by astrogeco** [comment]
@yammajamma can you update the "Expected behavior changes" above with a summary of the hotfixes?

**Pull request merged**
