### PR TITLE
Fix #692, fix or statements

### LINKED ISSUE #692: Incorrect assertions in network-api-test
**Describe the bug**
The test is not correctly checking the return value in a few places.  For example:

https://github.com/nasa/osal/blob/9407cdf0be77521d850c587c0f749779c4656c3e/src/tests/network-api-test/network-api-test.c#L129

https://github.com/nasa/osal/blob/9407cdf0be77521d850c587c0f749779c4656c3e/src/tests/network-api-test/network-api-test.c#L133

**To Reproduce**
Make the subject code return something other than OS_SUCCESS or OS_ERR_NOT_IMPLEMENTED.  Assert statement will still be true.

**Expected behavior**
Probably should be `actual == OS_SUCCESS || actual == OS_ERR_NOT_IMPLEMENTED`

**System observed on:**
N/A - inspection

**Reporter Info**
Joseph Hickey, Vantage Systems, Inc.

### PR DESCRIPTION
**Pull request by zanzaben**
**Describe the contribution**
Fixes #692
fixed the or statement to correctly compare against both options. 

**Testing performed**
Build and run unit test

**Expected behavior changes**
will correctly cath failures when they happen

**System(s) tested on**
Ubuntu 20.04

**Contributor Info - All information REQUIRED for consideration of pull request**
Alex Campbell GSFC

### CODE REVIEW

**Review by skliper — APPROVED** [review]

**Comment by skliper** [comment]
How about" Fix #692, Resolve typos in unit test assert OR statements"?

**Review by skliper — APPROVED** [review]

**Review by skliper — CHANGES_REQUESTED** [review]
Looking closer I'd recommend something like:
```
if (actual == OS_ERR_NOT_IMPLEMENTED)
{
    UtPrintf("XXX API not implemented");
}
else
{
... do rest of the test
}
```

**Review by skliper — CHANGES_REQUESTED** [review]
Needs auto-formatting applied, otherwise great improvement.

**Comment by skliper** [comment]
Side note - not implemented isn't actually considered and "error", test passes either way (and it's OK for OSAL/OS's to not implement all API functionality).

**Comment by zanzaben** [comment]
> Side note - not implemented isn't actually considered and "error", test passes either way (and it's OK for OSAL/OS's to not implement all API functionality).

Well then it shouldn't be called os_ERR_not_implemented

**Review by skliper — APPROVED** [review]
Good point!  In the context of FSW it is an error, and brings up that we should probably be flagging the not implemented cases as `UTASSERT_CASETYPE_NA` so they get explicitly counted/reported.  Lets address that as a separate issue though.

**Comment by astrogeco** [comment]
@skliper opened related issue to make finding "not implemented" items

**Pull request merged**
