### PR TITLE
Fix #424, Add looping wait for self exiting task

### LINKED ISSUE #424: Test  #7: osal-core-test Failure
**Describe the bug**
Test  #7: osal-core-test fails.  

**To Reproduce**
Note: this test was not readily repeatable, but it failed 2/10 times on this branch: 
fix413-Add-Reference-To-Osal-Users-Guide-From-ReadMe
1. Go to branch stated above
2. Run build/exe/cpu1/osal-core-test

**Expected behavior**
The test failed 2/10 times.  Specifically, failure is due to the code snippet noted below in  osal-core-test.c, line 138 where a small time delay is supposed to occur and the child task is perhaps not exiting before the OS_TaskDelete call happens, so it's returning success. 

**Code snips**
[ FAIL] 01.261 osal-core-test.c:138 - OS_TaskDelete, self exiting task

**System observed on:**
GNOME VM
OS: Ubuntu 18.04
Versions: OSAL 5.0.11.0

**Additional context**
This may be due to the VM delay.  

**Reporter Info**
Yasir Khan
NASA GSFC

### PR DESCRIPTION
**Pull request by skliper**
**Describe the contribution**
Loops the parent OS_TaskDelay until child task exits before testing OS_TaskDelete.  Avoids the test depending on system loading/performance with single delay approach.
Fix #424 

**Testing performed**
Steps taken to test the contribution:
1. Standard build, ran `osal-core-test -d` and observed Loop count of 1 (I've never experienced the failure, which if avoided would have a loop count > 1)

**Expected behavior changes**
Consistent osal-core-test execution status

**System(s) tested on**
 - Hardware: cFS Dev Server 3
 - OS: Ubuntu 18.04
 - Versions: Bundle + this commit

**Additional context**
Issue seen on dev server 4 and Mac OS

**Third party code**
None

**Contributor Info - All information REQUIRED for consideration of pull request**
Jacob Hageman - NASA/GSFC

### CODE REVIEW

**Comment by skliper** [comment]
@stanislaw @yammajamma - could you test on your systems that reported failure?  If you run with debug `osal-core-test -d | grep osa-core-test.c:134`, should see a loop count greater than 1 eventually, and if it passes shows the update fixed the issue.

**Comment by skliper** [comment]
Or pipe to a file so you can see the exit status... whatever.

**Comment by astrogeco** [comment]
CCB 20200422 - Add upper limit to loop, APPROVED

**Comment by skliper** [comment]
Added loop limit of 100, and assert

**Comment by skliper** [comment]
Tested with bundle, SIMULATION=native ENABLE_UNIT_TEST=true.  Passed

**Pull request merged**
