### PR TITLE
Fix #961, update OSAL Config Guide link

### LINKED ISSUE #961: OSAL Configuration Guide Link is broken in README
**Describe the bug**
The link to the OSAL Configuration Guide is broken in blob/main/README.md.

**To Reproduce**
Go to https://github.com/nasa/osal/blob/main/README.md and then click on the "Configuration Guide" link near the bottom of the file. It navigates to the old PDF file link.

**Expected behavior**
I expected the link to take me to the Markdown file in the repo.

**Code snips**
`See the [Configuration Guide](https://github.com/nasa/osal/blob/master/doc/OSAL-Configuration-guide.pdf) for more information.` (should reference doc/OSAL-Configuration-Guide.md).

**System observed on:**
Documentation only.

**Additional context**
N/A

**Reporter Info**
Ross Peters

### PR DESCRIPTION
**Pull request by rosspeters6**
**Describe the contribution**
Fixes github link in OSAL README.

**Testing performed**
- Went to https://github.com/rosspeters6/osal/blob/fix-961-update-osal-config-guide-link/README.md in Firefox to render Markdown
- Clicked "Configuration Guide" link at bottom of document
- Confirmed that Firefox navigated me to valid doc link: https://github.com/nasa/osal/blob/main/doc/OSAL-Configuration-Guide.md

Fixes #961 

**Expected behavior changes**
Link now properly navigates users to Config Guide documentation. 

**System(s) tested on**
 - Hardware: PC
 - OS: Ubuntu 18.04
 - Versions: Firefox 87.0 (64-bit)

**Additional context**
N/A

**Third party code**
N/A

**Contributor Info - All information REQUIRED for consideration of pull request**
Ross Peters

### CODE REVIEW

**Review by astrogeco — APPROVED** [review]

**Comment by astrogeco** [comment]
[CCB:2021-05-05](https://github.com/nasa/cFS/wiki/Community-CCB-Agenda:-May-05-2021) APPROVED

**Comment by astrogeco** [comment]
Hi Ross, thank you for the contribution! 

If you haven't done so already, please, **download, sign, and email** the appropriate Contributor License agreement to GSFC-SoftwareRelease@mail.nasa.gov and cfs-program@lists.nasa.gov.

[Corporate Contributor License agreement](https://github.com/nasa/cFE/blob/main/docs/GSC_18128_Corp_CLA_form_1219.pdf)
[Individual Contributor License agreement] (https://github.com/nasa/cFE/blob/main/docs/GSC_18128_Ind_CLA_form_1219.pdf)

**Comment by astrogeco** [comment]
@rosspeters6 did you see my message above?

**Comment by rosspeters6** [comment]
@astrogeco - thanks for your patience! I have submitted the signed agreement.

**Pull request merged**
