### PR TITLE
Fix #1171, check chmod return

### LINKED ISSUE #1171: Check Return Value of chmod
**Describe the bug**
Calling chmod(Filename, dststat.st_mode & 0xffffffc0U) without checking return value. This library function may fail and return an error code.

**Expected behavior**
Check the return value of chmod.

**Code snips**
https://github.com/nasa/osal/blob/42af0f73c952b4e4c7fbc06c97d354a1430f4ac3/ut_assert/src/uttools.c#L66

https://github.com/nasa/osal/blob/42af0f73c952b4e4c7fbc06c97d354a1430f4ac3/ut_assert/src/uttools.c#L115

**Additional context**
From Coverity: https://scan.coverity.com/projects/arielsadamsnasa-cfs-jsf-rules?tab=overview

Possible solution:
```
if (chmod(Filename, dststat.st_mode & ~(S_IRGRP | S_IWGRP | S_IXGRP | S_IROTH | S_IWOTH | S_IXOTH)) == 0) 
{
      chmod(Filename, dststat.st_mode & ~(S_IRGRP | S_IWGRP | S_IXGRP | S_IROTH | S_IWOTH | S_IXOTH));
      stat(Filename, &dststat);
}
```

**Reporter Info**
Ariel Adams, ASRC Federal

### PR DESCRIPTION
**Pull request by martintc**
**Describe the contribution**
- Fix #1171 

Check the return values on the calls to `chmod`

**Testing performed**
Using the CI/ID pipeline on github.

**Expected behavior changes**
No expected behavior change

**System(s) tested on**
 - OS: Ubuntu 18.04

**Additional context**
None

**Third party code**
None

**Contributor Info - All information REQUIRED for consideration of pull request**
Full name and company/organization/center of all contributors ("Personal" if individual work)
- If NASA Civil Servant Employee or GSFC Contractor on SES II
  - Address/email/phone and contract/task information (if applicable) must be on file
- Else if Company
  - **HAND SIGNED** Company CLA must be on file (once per release): [OSAL Company CLA](../docs/GSC_18370_Corp_CLA_form_1219.pdf)
- Else if Individual
  - **HAND SIGNED** Individual CLA must be on file (once per release): [OSAL Individual CLA](../docs/GSC_18370_Ind_CLA_form_1219.pdf)

JH edit: added fix keyword to autolink

### CODE REVIEW

**Comment by astrogeco** [comment]
One more thing, can you squash the commits and format the messages to match our standard? Check out https://github.com/nasa/cFS/blob/main/CONTRIBUTING.md#once-a-pull-request-ready-for-review

**Comment by martintc** [comment]
> One more thing, can you squash the commits and format the messages to match our standard? Check out https://github.com/nasa/cFS/blob/main/CONTRIBUTING.md#once-a-pull-request-ready-for-review for some guidelines

Formatting should be good to go. Hope I did the squashing of commits correctly. I will also work on getting the contributing license agreement in

**Comment by martintc** [comment]
As request, individual CLA is signed and sent to the email address provided on the form.

**Comment by astrogeco** [comment]
[CCB:2021-12-08](https://github.com/nasa/cFS/wiki/Community-CCB-Agenda:-December-08-2021) - REVIEW AGAIN
- Need to look into this and ensure it works with C99 and not posix

**Comment by skliper** [comment]
My mistake, I shouldn't have recommended using a POSIX function in utassert.  Will need to refactor slightly.

**Comment by skliper** [comment]
Adding the stat and chmod (original line 64-67) stems from trying to squash a "File created without restricting permissions" alert, and since there's no great way I'm aware of to do that w/ just C99 without introducing a TOCTOU alert... and even with POSIX dependency it still throws the original alert I think we should take a step back and remove the original change, accept that the user needs to have reasonable default permissions, and add a comment detailing our approach/disposition of the alert.  We really can't correct for the alert in a good way whenever creating files within the software.

**Comment by dzbaker** [comment]
CCB 8 September 2022: May just want to open issue to go back to old implementation and close this one.

**Pull request closed without merging**
