### PR TITLE
Integration Candidate: 2020-11-10

### LINKED ISSUE #637: OS_ModuleUnload() for statically loaded module may segfault
**Describe the bug**
Calling `OS_ModuleUnload()` on a statically loaded module will still attempt to call `dlclose()` but the handle is NULL because no module was loaded.  At least on Linux/Glibc this actually causes a segmentation fault.

**To Reproduce**
Using the CFE framework switch any app (e.g. sample_app) from a regular dynamic app to a static app.
Build and run CFE, then shutdown with CTRL+C.
The shutdown ends up calling `OS_DeleteAllObjects()` which in turn will trigger this bug - one gets a segfault instead of a clean exit.

**Expected behavior**
Should shutdown cleanly.

**System observed on:**
Ubuntu 20.04

**Reporter Info**
Joseph Hickey, Vantage Systems, Inc.

### LINKED ISSUE #641: Add OS_ModuleLoad flags to indicate symbol table visibility
**Is your feature request related to a problem? Please describe.**
On POSIX platforms with a real dynamic loader/shared object implementation, using the `RTLD_GLOBAL` flag to dlopen() can make it tricky or impossible to unload modules later.  This flag makes the symbols globally available to satisfy other relocations, and unloading of the module will be deferred or prevented entirely as long as the runtime loader thinks a symbol is being used.

This ultimately causes a requirement failure on this platform as documented in nasa/cfe#952 - because the module isn't _actually_ unloaded when `dlclose()` is called, and even though the new/replacement app module was loaded, CFE will end up restarting the original code, not the new (reloaded) code.

Loading a module with `RTLD_LOCAL` instead seems to prevent this issue - because the symbols are simply not made available for other modules/entities to use.  This ensures that when the time comes to unload the module, nothing else is referencing the module, and `dlclose()` actually does unload it.

But this LOCAL flag cannot be used for all modules, because libraries do need their symbols added to the global table, or else it will not be possible to load apps that depend on those libraries 

**Describe the solution you'd like**
Add a "flags" parameter onto the existing `OS_ModuleLoad()` API, so it becomes:

    int32 OS_ModuleLoad(osal_id_t *module_id, const char *module_name, const char *filename, uint32 flags)

The "flags" parameter can be used to indicate the symbol visibility.  A flag value of 0 should map to "global" - which is what the current implementation does - to make an easy transition for existing code.

In order to be able to look up an entry point in a module loaded with this option, this necessitates another new API:

    int32 OS_ModuleSymbolLookup(osal_id_t module_id, cpuaddr *SymbolAddress, const char *SymbolName)

Which is the same as `OS_SymbolLookup()` but accepts a module ID value and operates on that module, rather than on the global scope.  This should be the ID that was returned from the OS_ModuleLoad call.

For RTOS implementations that do not have this symbol visibility option they can ignore the flag, continue to map everything into the global symbol table as they currently do, and `OS_ModuleSymbolLookup` and `OS_SymbolLookup` become equivalent.

**Additional context**
Note that most all other OSAL "create" functions (tasks, queues, semaphores, etc) already have a "flags" parameter on the API, reserved for future use.  Unfortunately, this flags parameter was not part of the original `OS_ModuleLoad()` API definition, making it an exception to the pattern.  So by adding this, although it is a breaking change, it makes it more consistent with the rest of the APIs.

The alternative would be to define a separate `OS_ModuleLoadWithFlags()` API, but this pattern does not exist anywhere else, so it would continue to be an exception with respect to the overall OSAL API.

**Requester Info**
Joseph Hickey, Vantage Systems, Inc.

### PR DESCRIPTION
**Pull request by astrogeco**
**Describe the contribution**

Fix #637, static module unload fix
Fix #641, add flags to OS_ModuleLoad

**Testing performed**
Bundle CI on astrogeco: https://travis-ci.com/github/astrogeco/cFS/builds/200387877

**Expected behavior changes**

PR #638 -  Ensure that the handle is not NULL before invoking dlclose(). In particular the handle will be NULL for static modules. Shutdown after CTRL+C occurs normally (no segfault).

PR #643 - Add a "flags" parameter to OS_ModuleLoad() to indicate the desired symbol visibility:
- GLOBAL (0, the default, and matches current behavior)
- LOCAL which hides from other modules and prevents other modules from binding to symbols in this module, thereby ensuring/preserving the ability to unload in the future

CFE should use LOCAL flag for apps, and GLOBAL flags for libraries.

**System(s) tested on**

**Additional context**
Part of <https://github.com/nasa/cFS/pull/156>

**Third party code**
None

**Contributor Info - All information REQUIRED for consideration of pull request**
@jphickey

### CODE REVIEW

**Comment by astrogeco** [comment]
@jphickey Got a test failure 
https://travis-ci.com/github/astrogeco/cFS/jobs/432694405
```
/home/travis/build/astrogeco/cFS/cfe/fsw/cfe-core/src/es/cfe_es_apps.c: In function ‘CFE_ES_LoadModule’:

/home/travis/build/astrogeco/cFS/cfe/fsw/cfe-core/src/es/cfe_es_apps.c:371:22: error: too few arguments to function ‘OS_ModuleLoad’

         StatusCode = OS_ModuleLoad ( &ModuleId,

                      ^~~~~~~~~~~~~

In file included from /home/travis/build/astrogeco/cFS/osal/src/os/inc/osapi.h:115:0,

                 from /home/travis/build/astrogeco/cFS/cfe/fsw/cfe-core/src/inc/cfe.h:44,

                 from /home/travis/build/astrogeco/cFS/cfe/fsw/cfe-core/src/inc/private/cfe_private.h:32,

                 from /home/travis/build/astrogeco/cFS/cfe/fsw/cfe-core/src/es/cfe_es_apps.c:39:

/home/travis/build/astrogeco/cFS/osal/src/os/inc/osapi-os-loader.h:198:7: note: declared here

 int32 OS_ModuleLoad(osal_id_t *module_id, const char *module_name, const char *filename, uint32 flags);

       ^~~~~~~~~~~~~

cfe-core/CMakeFiles/cfe-core.dir/build.make:75: recipe for target 'cfe-core/CMakeFiles/cfe-core.dir/src/es/cfe_es_apps.c.o' failed

make[7]: *** [cfe-core/CMakeFiles/cfe-core.dir/src/es/cfe_es_apps.c.o] Error 1

CMakeFiles/Makefile2:6951: recipe for target 'cfe-core/CMakeFiles/cfe-core.dir/all' failed

make[6]: *** [cfe-core/CMakeFiles/cfe-core.dir/all] Error 2

Makefile:140: recipe for target 'all' failed

make[5]: *** [all] Error 2

CMakeFiles/native_default_cpu1-all.dir/build.make:57: recipe for target 'CMakeFiles/native_default_cpu1-all' failed

make[4]: *** [CMakeFiles/native_default_cpu1-all] Error 2

CMakeFiles/Makefile2:361: recipe for target 'CMakeFiles/native_default_cpu1-all.dir/all' failed

make[3]: *** [CMakeFiles/native_default_cpu1-all.dir/all] Error 2

CMakeFiles/Makefile2:208: recipe for target 'CMakeFiles/mission-all.dir/rule' failed

make[2]: *** [CMakeFiles/mission-all.dir/rule] Error 2

Makefile:227: recipe for target 'mission-all' failed

make[1]: *** [mission-all] Error 2

Makefile:120: recipe for target 'all' failed

make: *** [all] Error 2

The command "make" exited with 2.
```

**Comment by jphickey** [comment]
@astrogeco make sure the dependency is also pulled into the build:  nasa/cfe#1000

**Comment by astrogeco** [comment]
That's what I get for not reading the comments before merging...

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by astrogeco** [comment]
@jphickey doxygen error up next

```
You must fix doxygen warnings for "usersguide" before submitting a pull request

/home/travis/build/astrogeco/cFS/osal/src/os/inc/osapi-os-loader.h:198: warning: The following parameters of OS_ModuleLoad(osal_id_t *module_id, const char *module_name, const char *filename, uint32 flags) are not documented:

  parameter 'flags'

/home/travis/build/astrogeco/cFS/osal/src/os/inc/osapi-os-loader.h:148: warning: argument 'symbol_address' of command @param is not found in the argument list of OS_ModuleSymbolLookup(osal_id_t module_id, cpuaddr *SymbolAddress, const char *SymbolName)

/home/travis/build/astrogeco/cFS/osal/src/os/inc/osapi-os-loader.h:148: warning: argument 'symbol_name' of command @param is not found in the argument list of OS_ModuleSymbolLookup(osal_id_t module_id, cpuaddr *SymbolAddress, const char *SymbolName)

/home/travis/build/astrogec

**Comment by jphickey** [comment]
Doxygen issue is fixed on commit 3f5e8f3

(the force earlier was to just to revert an incomplete fix that I pushed too soon - its all good now).

**Pull request merged**
