### PR TITLE
Work #384, #640, #672, Minor fixes to osal config guide

### PR DESCRIPTION
**Pull request by Kronos3**
**Describe the contribution**
I noticed a few things missing from the documentation.
There were also duplicate entries in one of the tables

Partially addresses #384, #640, #672

**Testing performed**
(none)

**Expected behavior changes**
No impact to behavior

**System(s) tested on**
Gentoo Linux - amd64

**Contributor Info**
Andrei Tumbar (NASA JPL) andrei.tumbar@jpl.nasa.gov / andreitumbar@gmail.com

### CODE REVIEW

**Comment by skliper** [comment]
This is partially related to #672 and #384

**Comment by astrogeco** [comment]
Thanks for the contribution Andrei!

**Review by jphickey — APPROVED** [review]
This actually touches a couple spots that my previous PR also did, so we'll have to merge.  Looks good though.

**Comment by astrogeco** [comment]
Hi again @Kronos3, if you haven't done so already please, **download, sign, and email** the appropriate Contributor License agreement below to GSFC-SoftwareRelease@mail.nasa.gov and cfs-program@lists.nasa.gov.

[Corporate Contributor License agreement](https://github.com/nasa/cFE/blob/main/docs/GSC_18128_Corp_CLA_form_1219.pdf)
[Individual Contributor License agreement](https://github.com/nasa/cFE/blob/main/docs/GSC_18128_Ind_CLA_form_1219.pdf)

THANKS!

**Comment by Kronos3** [comment]
Hi @astrogeco, I submitted the license agreement, should I expect a reply (submitted 3 days ago)?

**Comment by astrogeco** [comment]
Thanks Andrei! 

Had some kinks in the process internally but we’re all squared away. I also saw you made some merges to the PR to square away conflicts, thank you for that. I’ll take it from here. If you want more details on how our merges typically work, check out our [contributing guide](https://github.com/nasa/cFS/blob/main/CONTRIBUTING.md).

Thanks for the contribution!

**Pull request merged**
