### PR TITLE
Fix #1279, rtems queue multi-size, mimic posix logic

### LINKED ISSUE #1279: RTEMS osal queue mixed sizes
**Describe the bug**
Im using queues to send variable length messages.
RTEMS queue get returns an error if the message queue returned size is not the max buffer size.
https://github.com/nasa/osal/blob/main/src/os/rtems/src/os-impl-queues.c#L235

This doesn't match the posix implementation.
https://github.com/nasa/osal/blob/main/src/os/posix/src/os-impl-queues.c#L194

The above logic in `shared/src/osapi-queue.c` uses `OS_QUEUE_INVALID_SIZE` If the queue size is greater than the buffer provided.
```c
        if (size < queue->max_size)
        {
            /*
            ** The buffer that the user is passing in is potentially too small
            */
            *size_copied = 0;
            return_code  = OS_QUEUE_INVALID_SIZE;
        }
```

**To Reproduce**
Visual inspection.

**Expected behavior**
Follow the posix logic.

**Code snips**
See above

**System observed on:**
MIcroblaze

**Additional context**

**Reporter Info**
Sam Price

### PR DESCRIPTION
**Pull request by thesamprice**
**Checklist (Please check before submitting)**

* [X] I reviewed the [Contributing Guide](https://github.com/nasa/osal/blob/main/CONTRIBUTING.md).
* [X] I signed and emailed the appropriate [Contributor License Agreement](https://github.com/nasa/cFS/blob/main/CONTRIBUTING.md#contributor-license-agreement-cla) to GSFC-SoftwareRelease@mail.nasa.gov and copied cfs-program@lists.nasa.gov.

**Describe the contribution**
Refactor rtems queue to not do size check, and to mimic posix logic.

Fixes #1279 

**Testing performed**
Steps taken to test the contribution:
1. Build steps '...'
1. Execution steps '...'

**Expected behavior changes**
A clear and concise description of how this contribution will change behavior and level of impact.
 - API Change: xxx (if applicable)
 - Behavior Change: xxx (if applicable)
 - Or no impact to behavior

**System(s) tested on**
 - Hardware: [e.g. PC, SP0, MCP750]
 - OS: [e.g. Ubuntu 18.04, RTEMS 4.11, VxWorks 6.9]
 - Versions: [e.g. cFE 6.6, OSAL 4.2, PSP 1.3 for mcp750, any related apps or tools]

**Additional context**
Add any other context about the contribution here.

**Third party code**
If included, identify any third party code and provide text file of license

**Contributor Info - All information REQUIRED for consideration of pull request**
Full name and company/organization/center of all contributors ("Personal" if individual work)
 - Note CLAs apply to only software contributions.

### CODE REVIEW

**Comment by thesamprice** [comment]
The posix diff vs rtems diff
This is a more aggressive change than just deleting the size check.

image

**Comment by skliper** [comment]
Looks great!  Probably should use OSAL_SIZE_C to explicitly convert to size_t, I think that would avoid implicit conversion warnings if/when we ever do that analysis.  Looks like you'll need to run clang-format-10 (or fix formatting by hand) to squash the format workflow error.

**Comment by chillfig** [comment]
@thesamprice, would you please take a look at the unit test failure before merging?

**Comment by thesamprice** [comment]
@jphickey You recently added fix-1252-condvar-api.  Is there anything in this merge that would be causing that test to fail?

**Comment by thesamprice** [comment]
@chillfig Not sure why the last update fixed the unit test failure, but i guess adding OSAL_SIZE_C casting fixed it?

**Pull request merged**
