### PR TITLE
Fix #625, Apply standard formatting

### LINKED ISSUE #625: Apply standard formatting
**Is your feature request related to a problem? Please describe.**
Various formatting styles in codebase

**Describe the solution you'd like**
Apply standard formatting, if it's an improvement then submit for fasttrack (minimize impacts to open work).  If standard format requires hand mods, update such that application of standard format in the future doesn't require repeat modification.

**Describe alternatives you've considered**
Leave as-is if not an improvement.

**Additional context**
Preparation activity for certification code review.

**Requester Info**
Jacob Hageman - NASA/GSFC

### PR DESCRIPTION
**Pull request by skliper**
**Describe the contribution**
Fix #625 - apply standard formatting

**Testing performed**
Build/run unit tests, all pass.

**Expected behavior changes**
None, whitespace only

**System(s) tested on**
 - Hardware: cFS Dev Server
 - OS: Ubuntu 18.04
 - Versions: current bundle w/ this commit

**Additional context**
None

**Third party code**
None

**Contributor Info - All information REQUIRED for consideration of pull request**
Jacob Hageman - NASA/GSFC

### CODE REVIEW

**Review by CDKnightNASA — APPROVED** [review]

**Comment by skliper** [comment]
Scanned updates, net improvement (fixed some indent inconsistencies, removed extra lines, etc).  Nothing sufficiently mangled to require hand edit.

**Comment by astrogeco** [comment]
[CCB 2020-10-21](https://github.com/nasa/cFS/wiki/Community-CCB-Agenda:-October-21-2020) APPROVED

**Comment by skliper** [comment]
@astrogeco could this go in the current IC?  Would minimize impact and allow for me to progress with the other cleanup changes.

**Comment by astrogeco** [comment]
> @astrogeco could this go in the current IC? Would minimize impact and allow for me to progress with the other cleanup changes.

Might as well since I haven't merged it yet.

**Pull request merged**
