### PR TITLE
Fix #561, remove all deprecated code

### LINKED ISSUE #561: Remove OSAL deprecated code for next release
**Is your feature request related to a problem? Please describe.**
Now that the "5.1.x" release branch has been created, the next release should remove all code/functions that are currently marked as deprecated.

**Describe the solution you'd like**
Removal of all code currently contained within an `OMIT_DEPRECATED` conditional compile switch.

**Additional context**
The removal only applies to "main" branch - not the 5.1.x release branch, where it will continue to exist for that release series.  This assumes the next release (main) will become version 6.0.

There are other changes currently in development which do break some deprecated items - hence why I'd like to remove this sooner rather than later, as it saves the work of updating/fixing this old code if the intent is to remove it anyway.

**Requester Info**
Joseph Hickey, Vantage Systems, Inc.

### PR DESCRIPTION
**Pull request by jphickey**
**Describe the contribution**
In the next major OSAL release, this code will be no longer supported at all.  It should be removed early in the cycle
to avoid needing to maintain this compatibility code.

Fixes #561 

**Testing performed**
Build on native, RTEMS, and VxWorks and Confirm no issues/errors.  
Run all unit tests.
Sanity check CFE core.

**Expected behavior changes**
All old compatibility code is removed.  

**System(s) tested on**
Ubuntu 20.04
RTEMS 4.11.3 

**Additional context**
This code was already conditional on the `OSAL_OMIT_DEPRECATED` flag and as such the CCB has already tested/verified running the code in this configuration as part of CI scripts.

After this change, the build should be equivalent to the result of building with `OMIT_DEPRECATED=true`.

**Contributor Info - All information REQUIRED for consideration of pull request**
Joseph Hickey, Vantage Systems, Inc.

### CODE REVIEW

**Comment by astrogeco** [comment]
[CCB 2020-08-19](https://github.com/nasa/cFS/wiki/Community-CCB-Agenda:-August-19-2020) Need more discussion about deprecation timeline.

**Comment by astrogeco** [comment]
@jphickey can we do an intermediate commit to rename `OSAL_OMIT_DEPRECATED` to `OSAL_OMIT_DEPRECATED_5_0` before removing stuff. That way we can have a slightly more readable history. Thoughts?

**Comment by skliper** [comment]
@astrogeco - I thought we approved this one?  Further discussion required on the topic of removing elements deprecated this cycle before the release of Caelum.

**Comment by astrogeco** [comment]
> @astrogeco - I thought we approved this one? Further discussion required on the topic of removing elements deprecated this cycle before the release of Caelum.

Good point, I think that's what I was trying to say in my previous comment. Make sure there's nothing in the list that was deprecated for Caelum then remove anything that was deprecated for Bootes. 

I'll edit the CCB comment to reflect approval status

**Pull request merged**
