### PR TITLE
Fix #390, #392, osal select API unit tests and fixes

### LINKED ISSUE #377: OSAL Select APIs missing functional test
**Is your feature request related to a problem? Please describe.**
OS_SelectMultipe, OS_SelectSingle, OS_SelectFdZero, OS_SelectFdAdd, OS_SelectFdClear, OS_SelectFdIsSet all missing functional tests

**Describe the solution you'd like**
Add tests

**Describe alternatives you've considered**
None

**Additional context**
Certification issue.

**Requester Info**
Jacob Hageman - NASA/GSFC

### LINKED ISSUE #390: OS_SelectFdZero/OS_SelectFdAdd/OS_SelectFdClear/OS_SelectFdIsSet does not ensure Set is != NULL
**Describe the bug**
Users of these API's will cause a seg fault if they call these functions with a null pointer.

**To Reproduce**
Call OS_SelectFdZero(NULL), etc.

**Expected behavior**
These API's should return an error code when provided a NULL pointer.

**Code snips**
```
int32 OS_SelectFdZero(OS_FdSet *Set)
{  
   memset(Set,0,sizeof(OS_FdSet));
   return OS_SUCCESS;
} /* end OS_SelectFdZero */
```

**System observed on:**
Debian 9

**Additional context**

**Reporter Info**
Christopher.D.Knight@nasa.gov

### LINKED ISSUE #392: OS_SelectSingle(fd, &SelectFlags, timeout) users require OS_STREAM_STATE_READABLE/OS_STREAM_STATE_WRITABLE
**Describe the bug**
In order to use OS_SelectSingle() a user needs access to the #defines for OS_STREAM_STATE_READABLE and OS_STREAM_STATE_WRITABLE but they are contained in osal/src/os/shared/os-impl.h not in osal/src/os/inc/...

**To Reproduce**
Try to use the OS_SelectSingle API :)

**Expected behavior**
These #defines need to be moved to osal/src/os/inc

**Reporter Info**
Christopher.D.Knight@nasa.gov

### PR DESCRIPTION
**Pull request by CDKnightNASA**
**Describe the contribution**
fixes #390, fixes #392 -- adds unit tests for OSAL select API

Partially addresses #377, but full solution is a functional test that includes an operational scenario (actually select on a resource, confirm it pends until that resource is available).. bonus points if it illustrates the differences between OS's so it's clear from a user perspective what will work and what wont.

**Testing performed**
Built unit tests, tests passed.

**Expected behavior changes**
Externalizes enum for SelectSingle, ensures that pointers passed to SelectFd...() APIs are not null, ensures that pointer to SelectSingle is not null.

**System(s) tested on**
Debian 9

**Contributor Info - All information REQUIRED for consideration of pull request**
Christopher.D.Knight@nasa.gov

### CODE REVIEW

**Comment by skliper** [comment]
Note this doesn't actually address #377, I probably didn't do a good job describing the issue.  The "functional tests" that are missing are the ones similar to those in src/tests which don't use mocks/stubs.  The functional tests needed for #377 are against the API, and should demonstrate the functions work as intended.

The tests here are the "coverage test" part of unit tests.

**Comment by CDKnightNASA** [comment]
> The changes here are good, but shouldn't mark #377 as fixed (see my other comment).
> 
> Nitpick - preference would be to separate flight code changes and unit test changes into separate commits



> Note this doesn't actually address #377, I probably didn't do a good job describing the issue. The "functional tests" that are missing are the ones similar to those in src/tests which don't use mocks/stubs. The functional tests needed for #377 are against the API, and should demonstrate the functions work as intended.
> 
> The tests here are the "coverage test" part of unit tests.

No these do not use stubs, they do confirm the functional behavior of the Select API.

**Comment by CDKnightNASA** [comment]
> The changes here are good, but shouldn't mark #377 as fixed (see my other comment).
> 
> Nitpick - preference would be to separate flight code changes and unit test changes into separate commits

Wait, I'm sure I've been told to commit tests when I commit flight code... :D 

I can certainly re-split-out the null pointer check and enum move if the CCB would prefer as a separate pull. I did give a heads-up at last CCB that I would do a pull request incorporating all changes together, and heard no objections.

**Comment by skliper** [comment]
> > The changes here are good, but shouldn't mark #377 as fixed (see my other comment).
> > Nitpick - preference would be to separate flight code changes and unit test changes into separate commits
> 
> Wait, I'm sure I've been told to commit tests when I commit flight code... :D
> 
> I can certainly re-split-out the null pointer check and enum move if the CCB would prefer as a separate pull. I did give a heads-up at last CCB that I would do a pull request incorporating all changes together, and heard no objections.

Not a separate pull request, just separate commits.  I have to work on explaining what's in my head.  Another concept I describe poorly is "one topic per commit"... and grouping commits in a pull request.

**Comment by skliper** [comment]
Really just a nit in this case since the changes are very easy to review, straight forward, etc.  More complex changes where there's documentation, unit tests, flight code, etc my preference is smaller commits group into a single pull request.  Probably useful information for a contributor's guide...

**Comment by skliper** [comment]
> > The changes here are good, but shouldn't mark #377 as fixed (see my other comment).
> > Nitpick - preference would be to separate flight code changes and unit test changes into separate commits
> 
> > Note this doesn't actually address #377, I probably didn't do a good job describing the issue. The "functional tests" that are missing are the ones similar to those in src/tests which don't use mocks/stubs. The functional tests needed for #377 are against the API, and should demonstrate the functions work as intended.
> > The tests here are the "coverage test" part of unit tests.
> 
> No these do not use stubs, they do confirm the functional behavior of the Select API.

Worth a discussion at the CCB... I didn't immediately see where it shows that the select blocks as it's supposed to until a file becomes readable or writable, or a demonstration of the timeout and verification of reasonable timing.

**Comment by jphickey** [comment]
Should note that RTEMS doesn't really support `select` on bare files, the underlying system call only works on sockets.  It isn't a limitation of OSAL, its a limitation of the OS.  Therefore any functional test for `select` should focus on its use with sockets rather than files.

**Comment by skliper** [comment]
CCB 20200415 - APPROVED

**Pull request merged**
