### PR TITLE
Fix #1016, resolve discrepancies between module API and unit tests

### LINKED ISSUE #1016: Unit test status code discrepancies in osapi-module.h
**Is your feature request related to a problem? Please describe.**
The unit tests and API documentation should match, where all status codes in the API documentation are tested in a unit test, and likewise all codes being tested for are documented in the API.  

**Describe the solution you'd like**
Resolve the following mismatches:

File `src/os/inc/osapi-module.h`, function `OS_SymbolLookup()`:
- [x] OK: OS_ERROR
- [x] OK: OS_INVALID_POINTER
- [x] OK: OS_SUCCESS

File `src/os/inc/osapi-module.h`, function `OS_ModuleSymbolLookup()`:
- [x] OK: OS_ERROR
- [x] OK: OS_INVALID_POINTER
- [x] OK: OS_SUCCESS

File `src/os/inc/osapi-module.h`, function `OS_SymbolTableDump()`:
- [x] ONLY IN DOXY: OS_ERROR
- [ ] ONLY IN DOXY: OS_ERR_NOT_IMPLEMENTED
- [x] ONLY IN TEST: OS_FS_ERR_PATH_INVALID
- [x] OK: OS_INVALID_POINTER
- [ ] ONLY IN DOXY: OS_SUCCESS

File `src/os/inc/osapi-module.h`, function `OS_ModuleLoad()`:
- [x] ONLY IN DOXY: OS_ERROR
- [x] OK: OS_ERR_NAME_TAKEN
- [x] ONLY IN DOXY: OS_ERR_NAME_TOO_LONG
- [x] OK: OS_ERR_NO_FREE_IDS
- [x] OK: OS_INVALID_POINTER
- [x] OK: OS_SUCCESS

File `src/os/inc/osapi-module.h`, function `OS_ModuleUnload()`:
- [x] ONLY IN DOXY: OS_ERROR
- [x] ONLY IN TEST: OS_ERR_INVALID_ID
- [x] OK: OS_SUCCESS

File `src/os/inc/osapi-module.h`, function `OS_ModuleInfo()`:
- [x] OK: OS_ERR_INVALID_ID
- [x] OK: OS_INVALID_POINTER
- [x] OK: OS_SUCCESS

**Additional context**
Originally noted in #331, split into separate work items. 

**Requester Info**
Joseph Hickey, Vantage Systems, Inc.

### PR DESCRIPTION
**Pull request by jphickey**
**Describe the contribution**
Ensures correlation between the unit-tests and documented return values for the OSAL module API.

Fixes #1016

**Testing performed**
Build and run unit tests, re-run cross reference script to confirm

**Expected behavior changes**
All documented return values are tested or noted that they cannot be tested in functional test

**System(s) tested on**
Ubuntu

**Contributor Info - All information REQUIRED for consideration of pull request**
Joseph Hickey, Vantage Systems, Inc.

### CODE REVIEW

**Review by skliper — COMMENTED** [review]
- Add OS_ModuleUnload test with UNDEFINED ID returns INVALID ID, separate OS_ModuleInfo NULL and UNDEFINED ID test (overloaded, only checks for invalid pointer).
- OS_SymbolTableDump document OS_ERR_OUTPUT_TOO_LARGE and test with a size 0.
- OS_ModuleSymbolLookup overloads the error test, needs test with UNDEFINED ID returns INVALID ID

**Comment by jphickey** [comment]
See also #1052, my plan is to do another scrub of all tests to ensure OS_ERR_INVALID_ID is validated with both UNDEFINED and a nonzero bad ID value.

**Comment by jphickey** [comment]
Commit f384359c adds documentation and a test case for the OS_SymbolTableDump routines.

**Review by skliper — DISMISSED** [review]
Still needs fixing:
https://github.com/nasa/osal/blob/ebc789aec901a73ab05e95774407b5cdea9a4eaa/src/unit-tests/osloader-test/ut_osloader_symtable_test.c#L134

**Review by skliper — APPROVED** [review]

**Comment by jphickey** [comment]
Re-Pushed to correct commit message typo and squash commits where necessary

**Pull request merged**
