### PR TITLE
Fix #1172, Check Return Value for setsockopt

### LINKED ISSUE #1172: Check Return Value for setsockopt
**Describe the bug**
Calling setsockopt(impl->fd, 1, 2, &os_flags, 4U) without checking return value. This library function may fail and return an error code.

**Expected behavior**
Check return value for setsockopt

**Code snips**
https://github.com/nasa/osal/blob/42af0f73c952b4e4c7fbc06c97d354a1430f4ac3/src/os/portable/os-impl-bsd-sockets.c#L199

**System observed on:**
Coverity: https://scan.coverity.com/projects/arielsadamsnasa-cfs-jsf-rules?tab=overview

**Additional context**
Possible solution 
```
if (setsockopt(impl->fd, SOL_SOCKET, SO_REUSEADDR, &os_flags, sizeof(os_flags)) == 0)
{
    setsockopt(impl->fd, SOL_SOCKET, SO_REUSEADDR, &os_flags, sizeof(os_flags));
}
```

**Reporter Info**
Ariel Adams, ASRC Federal

### PR DESCRIPTION
**Pull request by himanshu007-creator**
**Describe the contribution**
A clear and concise description of what the contribution is.
- Include explicitly what issue it addresses [e.g. Fixes #X]

Resolves #1172
**Testing performed**
Steps taken to test the contribution:
1. Build steps '...'
1. Execution steps '...'

**Expected behavior changes**
A clear and concise description of how this contribution will change behavior and level of impact.
 - API Change: xxx (if applicable)
 - Behavior Change: xxx (if applicable)
 - Or no impact to behavior

**System(s) tested on**
 - Hardware: [e.g. PC, SP0, MCP750]
 - OS: [e.g. Ubuntu 18.04, RTEMS 4.11, VxWorks 6.9]
 - Versions: [e.g. cFE 6.6, OSAL 4.2, PSP 1.3 for mcp750, any related apps or tools]

**Additional context**
Add any other context about the contribution here.

**Third party code**
If included, identify any third party code and provide text file of license

**Contributor Info - All information REQUIRED for consideration of pull request**
Full name and company/organization/center of all contributors ("Personal" if individual work)
- If NASA Civil Servant Employee or GSFC Contractor on SES II
  - Address/email/phone and contract/task information (if applicable) must be on file
- Else if Company
  - **HAND SIGNED** Company CLA must be on file (once per release): [OSAL Company CLA](../docs/GSC_18370_Corp_CLA_form_1219.pdf)
- Else if Individual
  - **HAND SIGNED** Individual CLA must be on file (once per release): [OSAL Individual CLA](../docs/GSC_18370_Ind_CLA_form_1219.pdf)

### CODE REVIEW

**Comment by astrogeco** [comment]
Also try to fix the format differences found in https://github.com/nasa/osal/runs/3883153364?check_suite_focus=true
you can always run clang-format on the flagged files

**Comment by himanshu007-creator** [comment]
Hi @astrogeco, any updated on this PR status?

**Comment by skliper** [comment]
See comments in https://github.com/nasa/osal/issues/1172#issuecomment-1278942521.  @dmknutsen @dzbaker now manage the repo.

**Comment by dzbaker** [comment]
Will review at next CCB to consider closing PR.

**Review by jphickey — CHANGES_REQUESTED** [review]
I don't see what this achieves here - it's calling `setsockopt`, and if successful, calls `setsockopt` again with the same option?

As noted in the comments, its OK if the call to `setsockopt` fails, maybe the implementation doesn't support that option or something - but the connection will still work without it, so there is no need to do full checking on this call, as there is no recovery or alternate action required if it fails.

Recommend closing this PR without merge.

**Comment by dzbaker** [comment]
CCB 20 October 2022: Agreed to close without merging.

**Pull request closed without merging**
