### PR TITLE
Fix #555, provide typedef for OSAL ID

### LINKED ISSUE #555: OSAL should provide a typedef for "ID" values
**Is your feature request related to a problem? Please describe.**
The OSAL API uses `uint32` type to identify objects/resources in an abstract way.

**Describe the solution you'd like**
There should be a typedef for this.  For instance:

    typedef uint32 OS_id_t;

This typedef can then be used in all APIs rather than using `uint32` directly.

**Describe alternatives you've considered**
Keep using `uint32`.

**Additional context**
Providing a typedef is generally accepted as good practice in terms of future proofing the code.  This wouldn't change anything immediately, as the type will remain `uint32` as it currently is.

**Requester Info**
Joseph Hickey, Vantage Systems, Inc.

### PR DESCRIPTION
**Pull request by jphickey**
**Describe the contribution**
Introduces a new typedef, `osal_id_t`, in `common_types.h`, which should be used to represent an OSAL ID.  All API structures/functions are updated to use this typedef in place of the `uint32` type wherever it actually refers to an OSAL ID.

Adds inline functions for basic equality/validity check, and conversion back to bare integer for logging purposes.

Fixes #555 

**Testing performed**
Build and run all unit tests
Execute and sanity test CFE.

**Expected behavior changes**
Should be none.  As the `osal_id_t` typedef is a `uint32`, this is just an alias for the same thing.

**System(s) tested on**
Ubuntu 20.04
RTEMS 4.11.3

**Contributor Info - All information REQUIRED for consideration of pull request**
Joseph Hickey, Vantage Systems, Inc.

### CODE REVIEW

**Comment by jphickey** [comment]
Marked as draft because it depends on some other changes being merged first - removal of deprecated code in particular as otherwise this would require updating all of them to use the typedef (which doesn't seem worthwhile).

Actual change for review is in 4a90c436.  Will rebase after next cycle.

**Comment by jphickey** [comment]
Marking as CCB ready, the concept can be reviewed/discussed prior to rebase

**Comment by astrogeco** [comment]
[CCB 2020-08-19](https://github.com/nasa/cFS/wiki/Community-CCB-Agenda:-August-19-2020) APPROVED

**Comment by jphickey** [comment]
Rebased to integration-candidate - should be ready for merge

**Comment by jphickey** [comment]
NOTE - testing after rebase, I noticed there are some newly-written unit tests that will need to be updated to use `osal_id_t` rather than `uint32` i.e. `file-sys-add-fixed-map-api-test.c` and `network-api-test.c`.  I'll get these updated ASAP - please hold off on merge until then.

**Comment by jphickey** [comment]
Commit 0f54017 above updates the new test routines to use the typedef correctly/consistently.

Now this should be good to merge.

**Comment by jphickey** [comment]
Rebased to main again ... still hoping to get this into a build....

**Pull request merged**
